name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Clean Build Directory
        env:
          CCACHE_DISABLE: "1"
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          . "$idfPath\export.ps1"
          Set-Location $projectDir
          Write-Host "Cleaning build directory..."
          & "$idfPython" "$idfPath\tools\idf.py" fullclean

      - name: Setup ESP-IDF and Build Project
        env:
          CCACHE_DISABLE: "1"
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED" 
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          . "$idfPath\export.ps1"
          Set-Location $projectDir
          Write-Host "Building the project..."
          & "$idfPython" "$idfPath\tools\idf.py" build

  flash-local:
    runs-on: [self-hosted, windows]
    needs: build-local
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Flash Project to ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          . "$idfPath\export.ps1"
          Set-Location $projectDir
          Write-Host "Flashing the project..."
          & "$idfPython" "$idfPath\tools\idf.py" -p COM7 flash

  verify-local:
    runs-on: [self-hosted, windows]
    needs: flash-local
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Verify Firmware on ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          $projectDir = "button_LED"
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          Set-Location $projectDir
          Write-Host "Starting ESP32 monitor for 10 seconds..."
          $monitor = Start-Process -FilePath "$idfPython" -ArgumentList @("$idfPath\tools\idf.py", "-p", "COM7", "monitor") -NoNewWindow -PassThru -RedirectStandardOutput monitor_output.txt -RedirectStandardError monitor_error.txt
          Start-Sleep -Seconds 10
          if (-not $monitor.HasExited) {
            Write-Host "Stopping ESP32 monitor..."
            $monitor.Kill()
            $monitor.WaitForExit()
          }
          Write-Host "Monitor output:"
          Get-Content monitor_output.txt
          Write-Host "Monitor error output:"
          Get-Content monitor_error.txt