name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  #Paths for Work PC
  IDF_PATH: C:/Users/bzorba.B1-ES/esp/v5.4.2/esp-idf
  IDF_PYTHON: C:/Users/bzorba.B1-ES/.espressif/python_env/idf5.4_py3.13_env/Scripts/python.exe
  PROJECT_DIR: button_LED
  SERIAL_PORT: COM3
  #paths for Home PC
  #IDF_PATH: C:\Users\Xigmatek\esp\esp-idf
  #IDF_PYTHON: C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe
  #PROJECT_DIR: button_LED
  #SERIAL_PORT: COM7


jobs:
  build-local:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Clean Build Directory
        env:
          CCACHE_DISABLE: "1"
        run: |
          call "%IDF_PATH%\export.bat"
          cd /d "%PROJECT_DIR%"
          echo Cleaning build directory...
          "%IDF_PYTHON%" "%IDF_PATH%\tools\idf.py" fullclean
        shell: cmd

      - name: Setup ESP-IDF and Build Project
        env:
          CCACHE_DISABLE: "1"
        run: |
          call "%IDF_PATH%\export.bat"
          cd /d "%PROJECT_DIR%"
          echo Building the project...
          "%IDF_PYTHON%" "%IDF_PATH%\tools\idf.py" build
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

  flash-local:
    runs-on: [self-hosted, windows]
    needs: build-local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Flash Project to ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          call "%IDF_PATH%\export.bat"
          cd /d "%PROJECT_DIR%"
          echo Flashing the project...
          "%IDF_PYTHON%" "%IDF_PATH%\tools\idf.py" -p %SERIAL_PORT% flash
        shell: cmd

  verify-local:
    runs-on: [self-hosted, windows]
    needs: flash-local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Verify Firmware on ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          cd /d "%PROJECT_DIR%"
          echo Starting ESP32 monitor for 10 seconds...
          start "" /b "%IDF_PYTHON%" "%IDF_PATH%\tools\idf.py" -p %SERIAL_PORT% monitor > monitor_output.txt 2> monitor_error.txt
          timeout /t 10
          echo Stopping ESP32 monitor...
          for /f "tokens=2" %%a in ('tasklist ^| findstr /i "idf.py"') do taskkill /pid %%a /f
          echo Monitor output:
          type monitor_output.txt
          echo Monitor error output:
          type monitor_error.txt
        shell: cmd