name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell # Use PowerShell as the default shell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF and Install Dependencies
        run: |
          # Navigate to ESP-IDF directory
          cd C:\Users\Xigmatek\esp\esp-idf
          
          # Run the install script to ensure all dependencies are met
          # This is crucial for fixing the "python-deps" error
          .\install.bat 
          
          # Re-export the environment after installation
          # Use `.` to source the script and keep environment variables in the same session
          . .\export.ps1 

      - name: Build button_LED (local)
        run: |
          # Ensure we are in the project directory
          cd button_LED 
          # Build the project
          idf.py build

      - name: Flash button_LED to ESP32 (local)
        run: |
          # Ensure we are in the project directory
          cd button_LED
          # Flash the project to the ESP32
          idf.py -p COM7 flash --verbose

      - name: Verify firmware on ESP32
        run: |
          cd button_LED
          # Start the monitor in a background job
          $job = Start-Job { idf.py -p COM7 monitor }
          Start-Sleep -Seconds 5 # Give it some time to start
          Stop-Job $job # Stop the monitor job
          Receive-Job $job # Capture output (optional, can be removed if not needed)