name: ESP32 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up ESP-IDF (installs Python and sets env vars)
      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.4

      - name: Set environment variables for Makefile
        run: |
          echo "IDF_PATH=$IDF_PATH" >> $GITHUB_ENV
          echo "IDF_PYTHON=$IDF_PYTHON" >> $GITHUB_ENV
          echo "PROJECT_DIR=${{ github.workspace }}/hc05_bluetooth" >> $GITHUB_ENV
        shell: bash

      - name: Build hc05_bluetooth project
        run: make build
        env:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_PYTHON: ${{ env.IDF_PYTHON }}
          PROJECT_DIR: ${{ env.PROJECT_DIR }}

      - name: Patch CMakeLists.txt for button_LED
        run: |
          cd button_LED\main
          $srcs = (Get-ChildItem *.cpp | ForEach-Object { $_.Name }) -join '" "'
          Set-Content CMakeLists.txt "idf_component_register(SRCS `"$srcs`" INCLUDE_DIRS `".`")"
        shell: pwsh

      - name: Build button_LED project
        run: |
          echo "PROJECT_DIR=${{ github.workspace }}/button_LED" >> $GITHUB_ENV
          make build
        env:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_PYTHON: ${{ env.IDF_PYTHON }}
          PROJECT_DIR: ${{ env.PROJECT_DIR }}