name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF environment
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\install.bat
          call C:\Users\Xigmatek\esp\esp-idf\export.ps1

      - name: Build button_LED (local)
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\export.ps1
          cd button_LED
          idf.py build

      - name: Flash button_LED to ESP32 (local)
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\export.ps1
          cd button_LED
          idf.py -p COM7 flash --verbose

      - name: Verify firmware on ESP32
        shell: powershell
        run: |
          cd button_LED
          $job = Start-Job { idf.py -p COM7 monitor }
          Start-Sleep -Seconds 5
          Stop-Job $job
          Receive-Job $job
