name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell # Use PowerShell as the default shell for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF environment and dependencies
        run: |
          # Source the export script to set up environment variables
          . C:\Users\Xigmatek\esp\esp-idf\export.ps1

          # Check and install Python dependencies
          # This command should ideally be run after export.ps1
          python -m pip install --upgrade setuptools wheel
          python -m pip install -r C:\Users\Xigmatek\esp\esp-idf\requirements.txt
          # Or use the dedicated command if available in your IDF version
          # python C:\Users\Xigmatek\esp\esp-idf\tools\idf_tools.py install python-deps

      - name: Build button_LED (local)
        run: |
          # Source the export script again to ensure environment is set for this step
          . C:\Users\Xigmatek\esp\esp-idf\export.ps1
          cd button_LED
          idf.py build

      - name: Flash button_LED to ESP32 (local)
        run: |
          # Source the export script again
          . C:\Users\Xigmatek\esp\esp-idf\export.ps1
          cd button_LED
          idf.py -p COM7 flash --verbose

      - name: Verify firmware on ESP32
        run: |
          cd button_LED
          $job = Start-Job { idf.py -p COM7 monitor }
          Start-Sleep -Seconds 5
          Stop-Job $job
          Receive-Job $job