name: ESP32 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v4.4.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Build hc05_bluetooth project
        run: |
          sed -i 's|^PROJECT_DIR.*|PROJECT_DIR := $(pwd)/hc05_bluetooth|' Makefile
          make build

      - name: Patch CMakeLists.txt for button_LED
        run: |
          cd button_LED/main
          echo 'idf_component_register(SRCS "'$(ls *.cpp | tr '\n' '" "')'INCLUDE_DIRS ".")' > CMakeLists.txt

      - name: Build button_LED project
        run: |
          sed -i 's|^PROJECT_DIR.*|PROJECT_DIR := $(pwd)/button_LED|' Makefile
          make build