name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Flash
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED" 
          $env:CCACHE_TMPDIR = "$env:TEMP\ccache_temp"
          if (-not (Test-Path $env:CCACHE_TMPDIR)) {
              New-Item -ItemType Directory -Path $env:CCACHE_TMPDIR -Force
          }
          
          . "$idfPath\export.ps1"
          Set-Location $projectDir
          idf.py build
          idf.py -p COM7 flash

      - name: Verify firmware on ESP32
        run: |
          $projectDir = "button_LED"
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          
          Set-Location $projectDir
          
          Write-Host "Starting ESP32 monitor..."
          $monitorProcess = Start-Process -FilePath powershell -ArgumentList "-Command", " & '$idfPython' '$idfPath\tools\idf.py' -p COM7 monitor" -Wait -PassThru
          
          Start-Sleep -Seconds 10
          
          if ($monitorProcess.HasExited -eq $false) {
              Write-Host "Stopping ESP32 monitor..."
              $monitorProcess.Kill()
              $monitorProcess.WaitForExit()
          }