name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF environment
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\install.bat
          call C:\Users\Xigmatek\esp\esp-idf\export.bat

      - name: Build hc05_bluetooth (local)
        run: |
          cd hc05_bluetooth
          idf.py build

      - name: Flash hc05_bluetooth to ESP32 (local)
        run: |
          cd hc05_bluetooth
          idf.py -p COM7 flash

      - name: Patch CMakeLists.txt for button_LED (local)
        shell: powershell
        run: |
          cd button_LED/main
          $srcs = (Get-ChildItem *.cpp | ForEach-Object { $_.Name }) -join '" "'
          Set-Content CMakeLists.txt "idf_component_register(SRCS `"$srcs`" INCLUDE_DIRS `".`")"

      - name: Build button_LED (local)
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\export.bat
          cd button_LED
          idf.py build

      - name: Flash button_LED to ESP32 (local)
        run: |
          call C:\Users\Xigmatek\esp\esp-idf\export.bat
          cd button_LED
          idf.py -p COM7 flash --verbose

      - name: Verify firmware on ESP32
        shell: powershell
        run: |
          cd button_LED
          $job = Start-Job { idf.py -p COM7 monitor }
          Start-Sleep -Seconds 5
          Stop-Job $job
          Receive-Job $job
