name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF environment, build and flash
        run: |
          # Use `.` to source the script and keep environment variables in the same session
          . C:\Users\Xigmatek\esp\esp-idf\export.ps1
          
          # Change directory and run build/flash commands in the same session
          cd button_LED
          idf.py build
          
          idf.py -p COM7 flash --verbose

      - name: Verify firmware on ESP32
        run: |
          cd button_LED
          $job = Start-Job { idf.py -p COM7 monitor }
          Start-Sleep -Seconds 5
          Stop-Job $job
          Receive-Job $job