name: ESP32 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build hc05_bluetooth project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.4
          path: hc05_bluetooth


      - name: Patch CMakeLists.txt for button_LED
        run: |
          cd button_LED/main
          $srcs = (Get-ChildItem *.cpp | ForEach-Object { $_.Name }) -join '" "'
          Set-Content CMakeLists.txt "idf_component_register(SRCS `"$srcs`" INCLUDE_DIRS `".`")"
        shell: pwsh

      - name: Build button_LED project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.4
          path: button_LED