name: ESP32 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up ESP-IDF (installs Python and sets env vars)
      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.4

      - name: Build hc05_bluetooth project
        run: make build
        env:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_PYTHON: ${{ env.IDF_PYTHON }}
          PROJECT_DIR: ${{ github.workspace }}/hc05_bluetooth

      - name: Patch CMakeLists.txt for button_LED
        run: |
          cd button_LED\main
          $srcs = (Get-ChildItem *.cpp | ForEach-Object { $_.Name }) -join '" "'
          Set-Content CMakeLists.txt "idf_component_register(SRCS `"$srcs`" INCLUDE_DIRS `".`")"
        shell: pwsh

      - name: Build button_LED project
        run: make build
        env:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_PYTHON: ${{ env.IDF_PYTHON }}
          PROJECT_DIR: ${{ github.workspace }}/button_LED