name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF, Install Python Dependencies, and Build
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"

          # Set ESP-IDF environment
          . "$idfPath\export.ps1"

          # Configure ccache temporary directory if not set
          if (-not $env:CCACHE_TMPDIR) {
              Write-Host "Setting CCACHE_TMPDIR to a temporary location."
              $env:CCACHE_TMPDIR = Join-Path $env:TEMP "ccache_temp"
              if (-not (Test-Path $env:CCACHE_TMPDIR)) {
                  New-Item -ItemType Directory -Path $env:CCACHE_TMPDIR -Force
              }
          }

          Set-Location $projectDir

          # Install Python dependencies
          Write-Host "Installing ESP-IDF Python dependencies..."
          & "$idfPython" "$idfPath\tools\idf_tools.py" install python-deps

          # Build the project
          Write-Host "Building the project..."
          & "$idfPython" "$idfPath\tools\idf.py" build

      - name: Flash button_LED to ESP32 (local)
        run: |
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $projectDir = "button_LED"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"
          
          . "$idfPath\export.ps1"
          Set-Location $projectDir
          
          Write-Host "Flashing the project..."
          & "$idfPython" "$idfPath\tools\idf.py" -p COM7 flash

      - name: Verify firmware on ESP32
        run: |
          $projectDir = "button_LED"
          $idfPath = "C:\Users\Xigmatek\esp\esp-idf"
          $idfPython = "C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe"

          Set-Location $projectDir
          
          Write-Host "Starting ESP32 monitor for 10 seconds..."
          $monitorArgs = "$idfPython `"$idfPath\tools\idf.py`" -p COM7 monitor"
          $monitorProcess = Start-Process -FilePath powershell -ArgumentList "-Command", $monitorArgs -Wait -PassThru -RedirectStandardOutput "monitor_output.txt" -RedirectStandardError "monitor_error.txt"
          
          Start-Sleep -Seconds 10 
          
          if ($monitorProcess.HasExited -eq $false) {
              Write-Host "Stopping ESP32 monitor..."
              $monitorProcess.Kill()
              $monitorProcess.WaitForExit()
          }
          
          Write-Host "Monitor output:"
          Get-Content monitor_output.txt
          Write-Host "Monitor error output:"
          Get-Content monitor_error.txt