name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  #Paths for Work PC
  IDF_PATH: C:/Users/bzorba.B1-ES/esp/v5.4.2/esp-idf
  IDF_PYTHON: C:/Users/bzorba.B1-ES/.espressif/python_env/idf5.4_py3.13_env/Scripts/python.exe
  PROJECT_DIR: button_LED
  SERIAL_PORT: COM3
  #paths for Home PC
  #IDF_PATH: C:\Users\Xigmatek\esp\esp-idf
  #IDF_PYTHON: C:\Users\Xigmatek\.espressif\python_env\idf4.2_py3.8_env\Scripts\python.exe
  #PROJECT_DIR: button_LED
  #SERIAL_PORT: COM7


jobs:
  build-local:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Clean Build Directory
        env:
          CCACHE_DISABLE: "1"
        run: |
          . "${env:IDF_PATH}\export.ps1"
          Set-Location $env:PROJECT_DIR
          Write-Host "Cleaning build directory..."
          & "${env:IDF_PYTHON}" "${env:IDF_PATH}\tools\idf.py" fullclean

      - name: Setup ESP-IDF and Build Project
        env:
          CCACHE_DISABLE: "1"
        run: |
          . "${env:IDF_PATH}\export.ps1"
          Set-Location $env:PROJECT_DIR
          Write-Host "Building the project..."
          & "${env:IDF_PYTHON}" "${env:IDF_PATH}\tools\idf.py" build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

  flash-local:
    runs-on: [self-hosted, windows]
    needs: build-local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Flash Project to ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          . "${env:IDF_PATH}\export.ps1"
          Set-Location $env:PROJECT_DIR
          Write-Host "Flashing the project..."
          & "${env:IDF_PYTHON}" "${env:IDF_PATH}\tools\idf.py" -p $env:SERIAL_PORT flash

  verify-local:
    runs-on: [self-hosted, windows]
    needs: flash-local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: button_led_build
          path: button_LED/build

      - name: Disable ccache
        run: |
          $env:CCACHE_DISABLE="1"
          [System.Environment]::SetEnvironmentVariable("CCACHE_DISABLE", "1", "Process")

      - name: Verify Firmware on ESP32
        env:
          CCACHE_DISABLE: "1"
        run: |
          Set-Location $env:PROJECT_DIR
          Write-Host "Starting ESP32 monitor for 10 seconds..."
          $monitor = Start-Process -FilePath "${env:IDF_PYTHON}" -ArgumentList @("${env:IDF_PATH}\tools\idf.py", "-p", $env:SERIAL_PORT, "monitor") -NoNewWindow -PassThru -RedirectStandardOutput monitor_output.txt -RedirectStandardError monitor_error.txt
          Start-Sleep -Seconds 10
          if (-not $monitor.HasExited) {
            Write-Host "Stopping ESP32 monitor..."
            $monitor.Kill()
            $monitor.WaitForExit()
          }
          Write-Host "Monitor output:"
          Get-Content monitor_output.txt
          Write-Host "Monitor error output:"
          Get-Content monitor_error.txt