name: ESP32 CI Build & Flash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flash-local:
    runs-on: [self-hosted, windows]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Set up ESP-IDF
        run: call C:\Users\Xigmatek\esp\esp-idf\export.bat

      - name: Install ESP-IDF Python deps
        run: pip install -r C:\Users\Xigmatek\esp\esp-idf\requirements.txt

      - name: Build hc05_bluetooth
        run: |
          cd hc05_bluetooth
          idf.py build

      - name: Flash hc05_bluetooth to ESP32
        run: |
          cd hc05_bluetooth
          idf.py -p COM7 flash

      - name: Build button_LED
        run: |
          cd button_LED
          idf.py build

      - name: Flash button_LED to ESP32
        run: |
          cd button_LED
          idf.py -p COM7 flash
